/* =======================================
// Slide Script con effetto fade (ForumFree compatibile)
// Realizzato da Bowser e DarkStyle
// (C) 2009 http://ffmagazine.forumfree.net
// Versione: 1.0b - Ultima modifica: 20/07/2009 10:38
// Ringraziamenti speciali a:
// http://giulio.ganci.eu/2008/05/04/effetto-fade-con-javascript/
// ======================================= */
if(typeof(document.ElementById)!='function'){document.ElementById=function(obj){return(document.getElementById?document.getElementById(obj):document.all.obj)}}var slider=function(a,b,c,d,e,f,g,h){this.res=a?a:'mainboard';this.tab=b?b:'web';this.dominio=c?this.res+c:null;this.enfade=d?d:1;this.refresh=e?e:0;this.speed=f?f:10;this.orologio=g?g:1;this.timename=h?h:'orologio';this.load=function(){if(document.ElementById(this.timename)&&this.orologio){this.setTime();if(this.orologio==2)setInterval(this.res+'.setTime()',1000);document.ElementById(this.timename).onselect=function(){this.blur();return false};document.ElementById(this.timename).onfocus=function(){this.blur();return false}}if(document.ElementById(this.res)&&typeof(cat_nascoste)!='undefined')if(cat_nascoste.indexOf(this.dominio)!=-1)document.ElementById(this.res).className='nascosta'};this.close=function(){hidetbl=document.ElementById(this.res);hidetbl.className=hidetbl.className=='nascosta'?'':'nascosta';if(typeof(salvapreferenze)=='function')salvapreferenze(this.dominio,hidetbl.className)};this.setOpacity=function(obj,op){(document.all&&!window.opera)?document.ElementById(obj).style.filter="alpha(opacity="+op+")":document.ElementById(obj).style.opacity=op/100};this.fade=function(obj,t){time=Math.round(this.speed);frame=0;if(document.all&&!window.opera){document.ElementById(obj).style.height=0;document.ElementById(obj).style.minHeight=0}if(t==0){for(fd=0;fd<=100;++fd){setTimeout(this.res+".setOpacity('"+obj+"', "+fd+")",(time*frame));++frame}}else{for(fd=100;fd>=0;--fd){setTimeout(this.res+".setOpacity('"+obj+"', "+fd+")",(time*frame));++frame}}};this.show=function(e){ob=e.title;if(this.tab!=ob||this.refresh){if(this.enfade)this.fade(this.tab,1);document.ElementById(this.tab).className='nascosta';document.ElementById(ob).className='ww';if(this.enfade)this.fade(ob,0);this.tab=ob}};this.setTime=function(){var d=new Date(),AA=new String(d.getFullYear()),MM=new String(d.getMonth()+1),DD=new String(d.getDate()),hh=new String(d.getHours()),mm=new String(d.getMinutes());document.ElementById(this.timename).value='Sono le '+(hh.length==1?'0'+hh:hh)+':'+(mm.length==1?'0'+mm:mm)+' del '+(DD.length==1?'0'+DD:DD)+'/'+(MM.length==1?'0'+MM:MM)+'/'+AA}};
